# Generated by Django 5.2.4 on 2025-07-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Link Code',
                'verbose_name_plural': 'Link Codes',
            },
        ),
        migrations.CreateModel(
            name='InscritoPernoite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('vai_calebe', models.BooleanField(default=True)),
                ('camisa_calebe', models.BooleanField(default=True)),
                ('datas_disponiveis', models.CharField(blank=True, max_length=255, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('ip_usado', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('usercode_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulario.linkcode')),
            ],
        ),
    ]
