# Generated by Django 5.2.4 on 2025-07-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscritopernoite',
            name='ip_usado',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscritopernoite',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscritopernoite',
            name='usercodeUsado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
